### ISSUE TITLE
Newsletter collection failing due to updated Post JSON field

### ISSUE THREAD

**Issue by jeffreykennethli** [NHagar/substack-collection#2]
The field `prev_slug` in the Substack `posts/` endpoint has been replaced with `previous_post_slug`, see https://github.com/NHagar/substack-collection/blob/master/collection/newsletter_collect.py#L49 and an example `posts/` response: https://ava.substack.com/api/v1/posts/intuition-vs-execution

@NHagar Would you like me to make a PR for this?

Thanks for making this project, btw!

**Comment by NHagar** [comment]
Go for it!
